const CONFIG = {
    introTitle: 'Hí lu mình là ny cậu nè!',
    introDesc: `Yêu tớ không`,
    btnIntro: 'hihi',
    title: 'Yêu cậu mất rùi 😙',
    desc: 'Tớ đã say ngay từ lúc thấy nụ cười của cậu ',
    btnYes: 'Vẫn cứ là thích cậu <33',
    btnNo: 'Không, cậu à :3',
    question:'Trên thế giới hơn 7 tỉ người mà sao câu lại yêu tớ <3',
    btnReply: 'Gửi cho cậu <3',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: 'Tớ biết mà 🥰. Yêu cậu nhiều nhiều 😘😘',
    messDesc: 'Tớ iu cậu vailon.',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'http://fb.com' //link mess của các bạn. VD: https://m.me/nam.nodemy
